import { Poppins, Roboto, SUSE_Mono } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-head",
});

const suseMono = SUSE_Mono({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800"
  ],
  variable: "--font-mono",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-body",
});
export const metadata = {
  title: "Affordable. Reliable. Advanced.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=login"
        />
      </head>
      <body className={`${poppins.variable} ${roboto.variable} ${suseMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
